screen=INFO <empty> MOTION_BLUR_INTENSITY MOTION_BLUR_SAMPLES BLUR_MAX_VELOCITY DISABLE_HAND_BLUR DITHER_MODE USE_DEPTH_DILATION USE_DYNAMIC_SAMPLING MIN_SAMPLES MAX_SAMPLES

screen.columns=1
screen.DITHER_MODE.columns=2

sliders=MOTION_BLUR_INTENSITY MOTION_BLUR_SAMPLES BLUR_MAX_VELOCITY MIN_SAMPLES MAX_SAMPLES

texture.noise=textures/bluenoise.png