sliders=MOTION_BLUR_INTENSITY MOTION_BLUR_SAMPLES BLUR_MAX_VELOCITY NOISE_AMOUNT DISABLE_HAND_BLUR

MOTION_BLUR_INTENSITY=1.0
MOTION_BLUR_SAMPLES=12
BLUR_MAX_VELOCITY=0.05
NOISE_AMOUNT=0.5
DISABLE_HAND_BLUR=1