screen= INFO <empty> MOTION_BLUR_INTENSITY MOTION_BLUR_SAMPLES BLUR_MAX_VELOCITY DISABLE_HAND_BLUR DITHER_MODE

screen.columns = 1
screen.DITHER_MODE.columns = 2

sliders=MOTION_BLUR_INTENSITY MOTION_BLUR_SAMPLES BLUR_MAX_VELOCITY

texture.noise=textures/bluenoise.png